# Generated by Django 2.1.3 on 2018-12-07 16:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('url', models.URLField(blank=True)),
                ('open_hour', models.TimeField()),
                ('close_hour', models.TimeField()),
                ('description', models.TextField(blank=True, max_length=300)),
                ('address_1', models.CharField(max_length=128, null=True, verbose_name='address')),
                ('address_2', models.CharField(blank=True, max_length=128, verbose_name="address cont'd")),
                ('city', models.CharField(default='Reno', max_length=64, verbose_name='city')),
                ('state', localflavor.us.models.USStateField(default='NV', max_length=2, verbose_name='state')),
                ('code', models.CharField(max_length=5, null=True, verbose_name='zip code')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityType')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='interest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Profile'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityType'),
        ),
    ]
