# Generated by Django 2.1.3 on 2018-12-09 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20181209_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='activity_type',
            new_name='act_type',
        ),
    ]
