# Generated by Django 2.1.3 on 2019-02-08 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20181209_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTypeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.AddField(
            model_name='activitytypeline',
            name='act_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity'),
        ),
        migrations.AddField(
            model_name='activitytypeline',
            name='act_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityType'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ManyToManyField(through='activity.ActivityTypeLine', to='activity.ActivityType'),
        ),
    ]
