# Generated by Django 2.1.3 on 2019-02-09 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_remove_profile_birthday'),
        ('activity', '0005_savedactivity'),
    ]

    operations = [
    ]
