# Generated by Django 2.1.3 on 2019-03-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_savedactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='pic_url',
            field=models.URLField(blank=True),
        ),
    ]
