# Generated by Django 2.1.3 on 2019-03-05 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20190301_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='close_hour',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='open_hour',
        ),
    ]
