# Generated by Django 2.1.3 on 2019-03-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_auto_20190305_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='address_1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='address_2',
            new_name='address2',
        ),
        migrations.AddField(
            model_name='activity',
            name='display_phone',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='activity',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
