# Generated by Django 2.1.3 on 2019-03-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_auto_20190305_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='pic_url',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
