# Generated by Django 2.1.3 on 2019-03-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_auto_20190305_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='address2',
            field=models.CharField(max_length=128, null=True, verbose_name="address cont'd"),
        ),
    ]
