# Generated by Django 2.1.3 on 2019-04-03 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_activity_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 3, 11, 30, 47, 768967)),
            preserve_default=False,
        ),
    ]
