# Generated by Django 2.1.3 on 2019-04-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_activity_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='event_date',
            field=models.DateField(blank=True),
        ),
    ]
