# Generated by Django 2.1.3 on 2019-04-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0018_auto_20190403_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='length',
            field=models.IntegerField(null=True),
        ),
    ]
