# Generated by Django 2.1.3 on 2019-04-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0019_activity_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recommended',
            field=models.BooleanField(default=True),
        ),
    ]
