# Generated by Django 2.1.3 on 2019-05-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0020_profile_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='pic_url',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
